name: Tests
on: push
jobs:
  smoke:
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Build
        run: dotnet build
  unit:
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Test
        run: dotnet test
